spring:
  profiles:
    active: dev
  application:
    name: discodeit

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    web:
      pageable:
        default-page-size: 50
        max-page-size: 50
        one-indexed-parameters: false

  open-in-view: false

logging:
  level:
    root: info

discodeit:
  storage:
    type: local
    local:
      root-path: .discodeit/storage

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, loggers"
  info:
    env:
      enabled: true #환경 변수 정보를 info에서 쓸 수 있게 함

info:
  app:
    name: Discodeit
    version: 1.7.0
    java-version: 17
    spring-boot-version: 3.4.0
  config:
    datasource: # ${...} 표기법은 yml내의 다른 값을 그대로 갖고오라는 것
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto} # todo: 이렇게 작성하는 게 최선인가?
    storage:
      type: ${discodeit.storage.type} # 혹은 "s3"등 본인이 정한 방식 입력
      path: ${discodeit.storage.local.root-path} # 실제 저장 폴더 경로 작성 예) "/D:/codeit07/spring"
    multipart: # 파일 업로드 제한 크기를 Actuator에서 확인 가능
      max-file-size: ${spring.servlet.multipart.max-file-size}
      max-request-size: ${spring.servlet.multipart.max-request-size}
